on:
  push:
    paths:
      - "blueprints/mookunicorn/cs2_reactive_lights.yaml"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Gist
        uses: JasonEtco/update-gist@v2
        env:
          GIST_ID: e0efb5a367a2624cd9a8f1a2793c90d7
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
        with:
          filename: blueprints/mookunicorn/cs2_reactive_lights.yaml
